const dict = [
  ['what do you', 'wha-r-yah'],
  ["i'm going to", 'ahmma'],
  ["i'm gonna", 'ahmma'],
  ['going to', 'gonna'],
  ['when are you', 'whenriu'],
  ['because', "'cause"],
  // ['the ', 'dâh '],
  // ['you', 'yah'],
  ['what you', 'wha-tch-yah'],
  ['what do you', 'whatcha'],
  ['what have you', 'whatcha'],
  ['what are you', 'whatcha'],
  ['some more', "s'more"],
  ['used to', 'usta'],
  ['each of you', 'etchâviu'],
  ['you', 'yâh'],
  ['ve i', 'vi', false],
  ["isn't it", 'innit'],

  ['is there', 'isde:'],
  ['got to', 'garâh'],
  ['get to', 'ge.to'],
  ['i am', 'amm'],
  ["i'm", 'amm'],
  ['i will', 'auh'],
  ["i'll", 'auh'],
  ['t you', 'tchyah'],
  ['lot of s', 'loras'],
  ['a lot of', 'alotta'],
  ["should've", 'shulrah'],
  ['should have', 'shulrah'],
  ['could have', 'kurah'],
  ["could've", 'kurah'],
  ['want to', 'wanna'],
  ['to the', 'dârah'],
  ['which is', 'wichis'],
  ["would've", 'wurah'],
  ['would have', 'wurah'],
  ['must have', 'mustah'],
  ["must've", 'mustah'],
  ['ought to', 'oughrah'],
  ['do you', "d'you"],
  ["it's the", "it'sâh"],
  ['it is the', "it'sâh"],
  ['let just', 'letjust'],
  ['and also', 'enolsol'],
  ['and i also', 'enaolsol'],
  ['does this have', 'dâzês.ave'],
  ['does that', 'zat'],
  ['does this', 'dâzes'],
  ['as him', 'asim'],
  ['asked (him|her|if)', 'esT.$1'],
  ['of what', 'ovuat'],
  ['of\\b', 'ov'],
  ['as well as', 'as wellas'],
  ['if all goes well', 'ifal goesuell'],
  ['in our', 'inour'],
  ['trying to', 'truiaida '],
  ['taking to', 'teikinda'],
  ['get to', 'getâ'],
  ['it has', 'idas'],
  ['s have', '.sêv'],
  ['s ha', 'sa'],
  ['to that', 'râ that'],
  ['can i', 'canai'],
  ['i want you to', 'iuan tchê rê'],
  ["think i'm", 'thinkM'],
  ['heard anything', 'heardything'],
  ["there's a", 'reza'],
  ['With an accident', 'withanAccident'],
  ['why would they', 'ua rdey'],
  ['how would i', 'rauurai'],
  ['would he', 'uâre'],
  ["and I'd always", 'anai-rolways'],
  ["and it'll", "anir'll"],
  ['and this', 'anis'],
  ['t to\\b', '.râh'],
  ['t do\\b', 'tchâh'],
  ["why he's so", 'whaiSS so'],
  ['an example', 'anexample'],
  ["and that's", 'anets'],
  ['on that', 'onet'],
  ['getting that', 'geinat'],
  ['saying that', 'sayinat'],
  ['ing', 'in'],
  ['try to', 'tryrâ'],
  ['there is', 'theris'],
  ['watching a', 'watchina'],
  ['wish i', 'wishai'],
  ['with all', 'withou'],
  ['did i ever tell you', 'dirai ever tellyou'],
  ["How'd you", 'howdju'],
  ['about anything', 'abouranything'],
  ["l'm actually", "i'machually"],
  ['go together', 'gorogether'],
  // ['if he', 'ife'],
  ['build her', 'builder'],
  ['Maybe he', 'maybe i '],
  ["don't", 'ron'],
  ['died in there', 'dairiner'],
  ['them all', 'themou'],
  ['something in the', 'sometinina'],
  ['that in', 'tharin'],
  ['that is', 'thadis'],
  ['for the', 'fôthê'],
  // ['n you', 'nyou'],
  ['with this', 'withis'],
  ['should we', 'shou-we'],
  ['and i', 'enai'],
  ['n the', 'nnah'],
  ['have to', 'hafta'],
  ['t are you', 'tcha'],
  ['cause s', 'causs'],
  [' will', "'ll"],

  // ['where are you', 'whereya'],
  ['nt o', 'no'],
  ['\\bthem\\b', "'em"],
  ['\\bhim\\b', 'im'],
  ['\\bhis\\b', 'is'],
  ['\\bher\\b', 'er'],
  ['d l', 'dl'],
  ['t as', 'ttás'],
  ['t a', 'ttê'],
  ['n th', 'n'],
  ['d to', 'dâh'],
  ['t i', 'di'],
  ['d i', 'rai'],
  ['n one', 'nuone'],
  // ['d ', ''],
  ['t t', '.t'],
  // ['t ', ''],
  ["(n|v|p|g|s|m|k|(?<!f)f|th|r) (h|')?(a|e|i|o|w|u|y)", '.$1$3'],
  ['d a', 'da'],
  ['e ea', 'E'],
  ['ch o', "ch'o"],
  ['ne o', 'no'],
  ['t l ', 'tl'],
  ['m i', 'mi'],
  [' to\\b', ' râ'],
  ['he i', 'hei'],
  ['re o', 'ro'],
  ['n m', '.m'],
  ['if we', 'ife', false],
  ['on râ', 'on to'],
  ['(?<!h)e e', 'e'],
]

// dict.slice(90, 100).forEach(v => {
//   console.log(v[0], '👉', v[1])
// })

function generateConnected(frase) {
  console.log(frase)

  dict.reduce((acc, curr) => {
    const replaced = curr
      ? acc.replace(new RegExp(curr[0], 'gi'), curr[1])
      : acc
    if (acc !== replaced) console.log(replaced.replace('\n', ''))
    return replaced
  }, frase)
}

generateConnected(`

`)
//the women will go to the store because they want to buy shoes
// but we hadn't heard from Meg all day
// I tried to get to my kids, whose rooms were on opposite floors.
// i'd like each of you to pick a name
// so i want you to pay attention to this one
// We'll never know if we don't try to help her
// Thought I was supposed to stay in my room for the rest of my life
// The truth is, this technology is in its infancy,
// I don't want you to get the impression
// by then and I went on the
